[package]
name = "hacktor"
version = "0.1.0"
authors = ["Masterchef365 <duncan.freeman1@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = "1.2"
kiss3d = "0.22"
nalgebra = { version = "0.19", features = ["serde-serialize"] }
